prefix ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>

select * where {
    ?X a ub:Student ;
       ub:advisor ?Y ;
       ub:takesCourse ?Z .
    ?Y a ub:Faculty ;
       ub:teacherOf ?Z .
    ?Z a ub:Course .
}