prefix ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>

select * where {
    ?X a ub:Chair ;
       ub:worksFor ?Y .
    ?Y a ub:Department ;
       ub:subOrganizationOf <http://www.University0.edu> .
}