prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix td: <http://www.w3c.org/wot/td#>
prefix sosa: <http://www.w3.org/ns/sosa/>
prefix saref: <https://w3id.org/saref#>

select ?val ?pow where {
    ?p <http://example.org/curVal> ?val .
    bind (<javascript:Math.pow>(?val - 5, 0.5) as ?pow)
}